### ISSUE TITLE
裁剪

### ISSUE THREAD

**Issue by DJsunshine** [aggboy/pic-cropper#1]

**Comment by aggboy** [comment]
因为 图片没有 加载完成的话 会导致裁剪图片 失败

**Comment by aggboy** [comment]
图片 分为本地图片 以及 网络图片 1 本地图片的话 最好在 onload 图片加载完成这个勾子函数 进行       
 2网络图片 则需要调用微信小程序api 下载下来在进行裁剪   并且有个小坑的就是 drawImage 时候 必须在其回调函数 最好加上定时器 延迟生成 这样可以保证图片 有效生成
